# Generated by Django 4.2.5 on 2023-12-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElevatorSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_name", models.CharField(max_length=32)),
                ("max_floor", models.IntegerField()),
                ("number_of_elevators", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elevator_number", models.IntegerField()),
                ("current_floor", models.PositiveSmallIntegerField(default=0)),
                ("is_operational", models.BooleanField(default=True)),
                ("is_door_open", models.BooleanField(default=True)),
                (
                    "running_status",
                    models.IntegerField(
                        choices=[
                            (1, "Going Up"),
                            (0, "Standing Still"),
                            (-1, "Going Down"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "elevator_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.elevatorsystem",
                    ),
                ),
            ],
        ),
    ]
