# Generated by Django 4.2.5 on 2023-12-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElevatorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_floor", models.PositiveSmallIntegerField()),
                ("destination_floor", models.PositiveSmallIntegerField()),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "elevator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.elevator"
                    ),
                ),
            ],
        ),
    ]
