# Generated by Django 4.2.5 on 2023-12-12 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_elevatorrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevator",
            name="elevator_number",
        ),
        migrations.AddField(
            model_name="elevator",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Datetime when this object was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="elevator",
            name="modified_on",
            field=models.DateTimeField(
                auto_now=True, help_text="Datetime when this object was last modified"
            ),
        ),
        migrations.AddField(
            model_name="elevatorrequest",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Datetime when this object was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="elevatorrequest",
            name="modified_on",
            field=models.DateTimeField(
                auto_now=True, help_text="Datetime when this object was last modified"
            ),
        ),
        migrations.AddField(
            model_name="elevatorsystem",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Datetime when this object was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="elevatorsystem",
            name="modified_on",
            field=models.DateTimeField(
                auto_now=True, help_text="Datetime when this object was last modified"
            ),
        ),
        migrations.AlterField(
            model_name="elevator",
            name="current_floor",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Current floor"
            ),
        ),
        migrations.AlterField(
            model_name="elevator",
            name="elevator_system",
            field=models.ForeignKey(
                help_text="ID of elevator system , from which system this elevator belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.elevatorsystem",
            ),
        ),
        migrations.AlterField(
            model_name="elevator",
            name="is_door_open",
            field=models.BooleanField(
                default=True, help_text="Whether the door is open or not."
            ),
        ),
        migrations.AlterField(
            model_name="elevator",
            name="is_operational",
            field=models.BooleanField(
                default=True, help_text="Whether the elevator is operational or not."
            ),
        ),
        migrations.AlterField(
            model_name="elevator",
            name="running_status",
            field=models.IntegerField(
                choices=[(1, "Going Up"), (0, "Standing Still"), (-1, "Going Down")],
                default=0,
                help_text="Running status of elevator means, UP,DOWN..",
            ),
        ),
        migrations.AlterField(
            model_name="elevatorrequest",
            name="destination_floor",
            field=models.PositiveSmallIntegerField(
                help_text="Destination floor at which user wants to go."
            ),
        ),
        migrations.AlterField(
            model_name="elevatorrequest",
            name="elevator",
            field=models.ForeignKey(
                help_text="ID of elevator which is requested by user.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.elevator",
            ),
        ),
        migrations.AlterField(
            model_name="elevatorrequest",
            name="request_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time at which user requested for elevator.",
            ),
        ),
        migrations.AlterField(
            model_name="elevatorrequest",
            name="requested_floor",
            field=models.PositiveSmallIntegerField(
                help_text="Requested floor by user."
            ),
        ),
        migrations.AlterField(
            model_name="elevatorsystem",
            name="max_floor",
            field=models.IntegerField(help_text="Maximum floor in a elevator system"),
        ),
        migrations.AlterField(
            model_name="elevatorsystem",
            name="number_of_elevators",
            field=models.PositiveIntegerField(
                help_text="Maximum number of elevators in a elevator system"
            ),
        ),
        migrations.AlterField(
            model_name="elevatorsystem",
            name="system_name",
            field=models.CharField(help_text="Name of elevator system", max_length=32),
        ),
    ]
