# Generated by Django 4.2.5 on 2023-12-15 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_elevator_elevator_number_elevator_created_on_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elevatorsystem",
            old_name="system_name",
            new_name="name",
        ),
    ]
