# Generated by Django 4.2.5 on 2023-12-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_system_name_elevatorsystem_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="elevatorsystem",
            constraint=models.CheckConstraint(
                check=models.Q(("max_floor__gte", 1)), name="max_floor_cannot_be_zero"
            ),
        ),
    ]
